# Site settings
title: mohsen
description:  a personal blog where I write about software engineering, productivity, hunting down bugs and products I like
url:  https://mohsen.dev
twitter_username: coybit
github_username:  coybit
tagline: My personal blog where I write about software engineering
twitter:
  username: coybit
  card: summary

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
